### PR TITLE
use list instead set to keep the include files order

### PR DESCRIPTION
**Pull request by barbara-darkshot**

### CODE REVIEW

**Comment by jfboismenu** [comment]
Thank you for your presentation today @barbara-darkshot ! Could you send us the changes for the `template_includes.py` as well?

**Comment by barbara-darkshot** [comment]
Hi @jfboismenu , I'm not sure if the comment section is the right place to push my code changes :)
Let me know if you prefer an email or if I have to open/update a pull request.

Cheers!

[template_includes.zip](https://github.com/shotgunsoftware/tk-core/files/2639991/template_includes.zip)

**Comment by jfboismenu** [comment]
Haha, no, I meant please push the changes to the branch so we have everything when we're ready to merge. :)

**Comment by jfboismenu** [comment]
Merging into a branch to complete writing tests

**Pull request merged**
