### PR TITLE
Fixed git_descriptor so it properly finds latest forked versions when a version pattern is specified

### PR DESCRIPTION
**Pull request by benoit-leveau**
Rewrote most of _find_latest_by_pattern() so it process all patterns with the same loop, no matter how many 'x' are used.

The benefit is that it now works with forked versions, eg. a pattern of v4.x.x will find v4.0.2.1 (which wasn't the case before the change).

There's no limit on the number of additional levels, ie. a git tag of v4.0.2.1.2.3 will be properly handled.
If we want to enforce there's at max one additional level (for forked versions), it's just a matter of changing line 212:
<pre> if re.match("^v([0-9]+|x)(.([0-9]+|x)){2,}$", pattern):</pre>
into
<pre>  if re.match("^v([0-9]+|x)(.([0-9]+|x)){2,3}$", pattern):</pre>

With the change, it also means that configuration files can indicate they require a forked version by adding an extra 'x', eg. a pattern of v4.0.x.x will match v4.0.2.1 but not v4.0.3. This could be useful if you want to make sure the tank updates command ignore non-forked versions of an app/engine/framework.

This has been tested on an entire configuration and produced the expect output so I'm fairly confident it works in all cases, but as I tested only on Linux and it's a core change I recommend it's thoroughly tested on your side!

### CODE REVIEW

**Comment by manneohrstrom** [comment]
Great! Super! Thanks Benoit! I'll ticket this up so that we can get it QAed - will add to our next sprint.

**Comment by manneohrstrom** [comment]
Update: Looking at this now!

**Comment by benoit-leveau** [comment]
Ok, let me know if you have any questions.

Basically, there's two big changes:

the versions "tree" is now dictionaries all the way to the leaves
- { "1": { "2": [1,2,3], "4": [3,2,1] } }
+{1: {2: {1: {}, 2: {}, 3: {1: {}}}, 4: {1: {}, 2: {1: {}, 2: {}}, 3: {}}}} 

instead of different cases depending on where the "x" was located, it's now one code handling all the cases.

**Comment by manneohrstrom** [comment]
Ready for internal CR and QA in #223. Closing this one. Thanks benoit!

**Comment by manneohrstrom** [comment]
Update: This is now released as part of core 16.41. Thanks!

**Pull request closed without merging**
