### PR TITLE
[SHOT-4203] Added SGTK_PROJ_THUMB_OLD to environment_variables.rst

### PR DESCRIPTION
**Pull request by rob-aitchison**

### CODE REVIEW

**Comment by rob-aitchison** [comment]
Hi @shaynacohen , this PR review request may have been lost with the other one in the docs repo the other day. Please take a look when you can - thank you!

**Comment by rob-aitchison** [comment]
Will merge when next tk-desktop is released.

**Comment by rob-aitchison** [comment]
This is just a docs update for the variable.

**Review by carlos-villavicencio-adsk — APPROVED** [review]
LGTM!

**Pull request merged**
