### PR TITLE
SG-35087 Stop masking exceptions

### PR DESCRIPTION
**Pull request by carlos-villavicencio-adsk**
Sometimes we have support cases with messages like:

```
[33532 DEBUG sgtk.core.descriptor.io_descriptor.appstore] ...could not establish connection: 'SSLCertVerificationError' object has no attribute 'message'
```

```
File "C:\Users\xxxxxxxx\cfg\install\core\scripts\tank_cmd.py", line 1494, in run_engine_cmd
'"tank unregister_folders /path/to/folder"' % exc.message
AttributeError: 'TankInitError' object has no attribute 'message'
```

Turns out tk-core is raising an error the moment the error is handled. 
This PR attempts to fix this by gracefully getting the error description.

### CODE REVIEW

**Comment by carlos-villavicencio-adsk** [comment]
I cannot make codecov happy even adding the test it wanted 😢

**Review by julien-lang — COMMENTED** [review]
Why were we using the `message` parameter before and it does not work anymore? 
Did something change? Is it another Python 2->3?

**Comment by carlos-villavicencio-adsk** [comment]
@julien-lang Seems like a Py2 Py3 problem. It seems like we were relying on httpllib2 on Py2. I tried using `getattr` but we might end up losing the error message.

**Review by julien-lang — APPROVED** [review]
LGTM!

**Pull request merged**
